- id: '1713872447639'
  alias: Check Batteries Status
  description: ''
  use_blueprint:
    path: Blackshome/low-battery-notifications-and-actions.yaml
    input:
      include_time: time_enabled
      weekday_options:
      - mon
      - thu
      - fri
      - sat
      - sun
      - tue
      - wed
      include_easy_notify: enable_easy_notify
      include_persistent_notification: enable_persistent_notification
      notify_device:
      - 1cf8a114b9e0de46add05170adbbe0f9
      - 06cd8da3d9fe96805b3bc6afaca7f192
- id: '1713872513971'
  alias: Batteries Status
  description: ''
  use_blueprint:
    path: Blackshome/low-battery-notifications-and-actions.yaml
    input:
      include_time: time_enabled
      include_easy_notify: enable_easy_notify
      include_persistent_notification: enable_persistent_okay_notification
      notify_device:
      - 1cf8a114b9e0de46add05170adbbe0f9
      - 06cd8da3d9fe96805b3bc6afaca7f192
