###############################################################################
# THE HOME ASSISTANT CONFIGURATION FILE - MOTHER OF ALL CONFIG FILES
###############################################################################

## Core Configuration. Do not remove.
homeassistant:
  name: Home
  latitude: !secret latitude_home
  longitude: !secret longitude_home
  elevation: 0
  internal_url: !secret internal_url
  external_url: !secret external_url

## Packages
## https://www.home-assistant.io/docs/configuration/packages/
#packages: !include_dir_named includes/packages

#default_config:
#wake_on_lan:

tts:
  - platform: google_translate

energy:

recorder:
  purge_keep_days: 10
  auto_purge: true
  auto_repack: true
  exclude:
    domains:
      - device_tracker
      - media_player
      - uptime
      - time_date
      - worldclock
    entity_globs:
      - sensor.clock*
      - sensor.date*
      - sensor.glances*
      - sensor.load_*m
      - sensor.time*
      - sensor.uptime*
    entities:
      - camera.front_door
      - sensor.home_assistant_v2_db
      - sensor.memory_free
      - sensor.memory_use
      - sensor.memory_use_percent
      - sensor.processor_use
      - weather.openweathermap

  #automation: !include automations.yaml
#sensor: !include_dir_list includes/sensors/
#script: !include includes/script/scripts.yaml
#scene: !include includes/scene/scenes.yaml
#ios: !include includes/actions/ios.yaml
#template: !include includes/templates/template.yaml
#input_boolean: !include_dir_merge_named includes/inputs/boolean
#input_number: !include_dir_merge_named includes/inputs/number

# see: https://github.com/allangood/rtlamr2mqtt#home-assistant-utility-meter-configuration-sample
# utility_meter:
#   hourly_water:
#     source: sensor.water_meter
#     cycle: hourly
#   daily_water:
#     source: sensor.water_meter
#     cycle: daily
#   monthly_water:
#     source: sensor.water_meter
#     cycle: monthly

#   hourly_energy:
#     source: sensor.electricity_meter
#     cycle: hourly
#   daily_energy:
#     source: sensor.electricity_meter
#     cycle: daily
#     device_class: energy
#     unit_of_measurement: kWh
#   monthly_energy:
#     source: sensor.electricity_meter
#     cycle: monthly
