---
# Binary Sensors
# https://www.home-assistant.io/integrations/binary_sensor/

#- platform: ping
#  host: 8.8.8.8
#  name: WAN
#  scan_interval: 60
#
#- platform: ping
#  host: 192.168.11.1
#  name: pfSense
#  scan_interval: 60

- platform: template
  sensors:
    iphone_charge_state:
      device_class: battery_charging
      friendly_name: iPhone Charge State
      value_template: >
        {{ is_state('sensor.iphone_battery_state', 'Charging') }}

- platform: template
  sensors:
    window_status:
      friendly_name: 'Window Status'
      device_class: window
      value_template: >
        {% set sensors = [states.binary_sensor.sliding_door_kitchen,
                          states.binary_sensor.sliding_door_master_room,
                          states.binary_sensor.office_window_left_side] %}
        {{ sensors | selectattr('state','eq','on') | list | count > 0 }}